name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: export TERM = xterm
    - uses: actions/checkout@v4
    - name: Set TERM
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node: 22
    - run: npm ci
    - run: npm test
